# Generated by Django 4.0.2 on 2022-02-09 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('job_title', models.CharField(max_length=150)),
                ('about', models.CharField(max_length=500)),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='BooksandArticles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('data', models.DateTimeField()),
                ('address', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=64)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('length', models.IntegerField()),
                ('date', models.DateField()),
                ('ink', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='CoWorksers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('position', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EdicationalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(choices=[('Bachelor', 'Bachelor'), ('Master', 'Master'), ('Doctorate', 'Doctorate')], max_length=150)),
                ('field', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Studing', 'Studing'), ('Finished', 'Finished')], max_length=150)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=150)),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('data', models.DateTimeField()),
                ('length', models.IntegerField()),
                ('address', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('Trainee developer ', ' Trainee developer '), ('Junior developer ', ' Junior developer '), ('Mid-level developer ', ' Mid-level developer '), ('Senior developer ', ' Senior developer '), ('Leader ', ' Leader ')], max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='WorkHistoryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_category', models.CharField(choices=[('Administration, business and management', 'Administration, business and management'), ('Alternative therapies', 'Alternative therapies'), ('Animals, land and environment', 'Animals, land and environment'), ('Computing and ICT', 'Computing and ICT'), ('Construction and building', 'Construction and building'), ('Design, arts and crafts', 'Design, arts and crafts'), ('Education and training', 'Education and training'), ('Engineering', 'Engineerin'), ('Facilities and property services', 'Facilities and property services'), ('Financial services', 'Financial services'), ('Garage services', 'Garage services'), ('Hairdressing and beauty', 'Hairdressing and beauty'), ('Healthcare', 'Healthcare'), ('Heritage, culture and libraries', 'Heritage, culture and libraries'), ('Hospitality, catering and tourism', 'Hospitality, catering and tourism'), ('Languages', 'Languages'), ('Legal and court services', 'Legal and court services'), ('Manufacturing and production', 'Manufacturing and production'), ('Performing arts and media', 'Performing arts and media'), ('Print and publishing, marketing and advertising', 'Print and publishing, marketing and advertising'), ('Retail and customer services', 'Retail and customer services'), ('Science, mathematics and statistics', 'Science, mathematics and statistics'), ('Security, uniformed and protective services', 'Security, uniformed and protective services'), ('Social sciences and religion', 'Social sciences and religion'), ('Social work and caring services', 'Social work and caring services'), ('Sport and leisure', 'Sport and leisure'), ('Transport, distribution and logistics', 'Transport, distribution and logistics')], max_length=150)),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('Working', 'Working'), ('Finished', 'Finished')], max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='PrimaryInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Nothing', 'Nothing')], max_length=150)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], max_length=150)),
                ('military_service_status', models.CharField(choices=[('Educational Exemption', 'Educational Exemption'), ('Exempted', 'Exempted'), ('Completed', 'Completed'), ('Ongoing', 'Ongoing'), ('Not served yet', 'Not served yet')], max_length=150)),
                ('country', models.CharField(max_length=150)),
                ('convince', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=250)),
                ('date_of_birth', models.DateTimeField()),
                ('expected_salary', models.IntegerField()),
                ('job_category', models.CharField(choices=[('Administration, business and management', 'Administration, business and management'), ('Alternative therapies', 'Alternative therapies'), ('Animals, land and environment', 'Animals, land and environment'), ('Computing and ICT', 'Computing and ICT'), ('Construction and building', 'Construction and building'), ('Design, arts and crafts', 'Design, arts and crafts'), ('Education and training', 'Education and training'), ('Engineering', 'Engineerin'), ('Facilities and property services', 'Facilities and property services'), ('Financial services', 'Financial services'), ('Garage services', 'Garage services'), ('Hairdressing and beauty', 'Hairdressing and beauty'), ('Healthcare', 'Healthcare'), ('Heritage, culture and libraries', 'Heritage, culture and libraries'), ('Hospitality, catering and tourism', 'Hospitality, catering and tourism'), ('Languages', 'Languages'), ('Legal and court services', 'Legal and court services'), ('Manufacturing and production', 'Manufacturing and production'), ('Performing arts and media', 'Performing arts and media'), ('Print and publishing, marketing and advertising', 'Print and publishing, marketing and advertising'), ('Retail and customer services', 'Retail and customer services'), ('Science, mathematics and statistics', 'Science, mathematics and statistics'), ('Security, uniformed and protective services', 'Security, uniformed and protective services'), ('Social sciences and religion', 'Social sciences and religion'), ('Social work and caring services', 'Social work and caring services'), ('Sport and leisure', 'Sport and leisure'), ('Transport, distribution and logistics', 'Transport, distribution and logistics')], max_length=150)),
                ('first_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='f_name', to='cv.aboutme')),
                ('last_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='l_name', to='cv.aboutme')),
            ],
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('about', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cv.aboutme')),
                ('articles', models.ManyToManyField(to='cv.BooksandArticles')),
                ('contacs', models.ManyToManyField(to='cv.Contact')),
                ('cources', models.ManyToManyField(to='cv.Courses')),
                ('cowork', models.ManyToManyField(to='cv.CoWorksers')),
                ('education', models.ManyToManyField(to='cv.EdicationalDetail')),
                ('info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cv.primaryinfo')),
                ('languages', models.ManyToManyField(to='cv.Languages')),
                ('projects', models.ManyToManyField(to='cv.Projects')),
                ('skills', models.ManyToManyField(to='cv.Skills')),
                ('softwares', models.ManyToManyField(to='cv.Software')),
                ('works', models.ManyToManyField(to='cv.WorkHistoryDetail')),
            ],
        ),
    ]
