# Generated by Django 4.0.2 on 2022-02-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_remove_skills_title_remove_software_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='picture',
            field=models.ImageField(upload_to='archivos'),
        ),
    ]
