# Generated by Django 4.0.2 on 2022-02-12 18:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cv', '0004_alter_aboutme_owner_picture_alter_aboutme_picture'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Picture',
            new_name='pic',
        ),
    ]
